/* eslint-disable camelcase */
export const PRIVACY_POLICY_GET_REQUEST = "PRIVACY_POLICY_GET_REQUEST";
export const PRIVACY_POLICY_GET_SUCCESS = "PRIVACY_POLICY_GET_SUCCESS";
export const PRIVACY_POLICY_GET_ERROR = "PRIVACY_POLICY_GET_ERROR";
export const PRIVACY_POLICY_GET_RESET = "PRIVACY_POLICY_GET_RESET";